{% set name = "pytest-freezer" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pytest_freezer-{{ version }}.tar.gz
  sha256: 21bf16bc9cc46bf98f94382c4b5c3c389be7056ff0be33029111ae11b3f1c82a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - pytest >=3.6
    - freezegun >=1.0

test:
  imports:
    - pytest_freezer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-freezer
  summary: Pytest plugin providing a fixture interface for spulec/freezegun
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
