{% set name = "pytest-freezer" %}
{% set version = "0.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest_freezer-{{ version }}.tar.gz
  sha256: 8ee2f724b3ff3540523fa355958a22e6f4c1c819928b78a7a183ae4248ce6ee6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.6
    - pytest >=3.6
    - freezegun >=1.0

test:
  imports:
    - pytest_freezer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pytest-dev/pytest-freezer
  summary: Pytest plugin providing a fixture interface for spulec/freezegun
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
